
version: '3'

services:
    postgres:
        container_name: postgres
        image: postgres:latest
        hostname: db
        restart: unless-stopped
        ports:
            - "6543:5432"
        env_file:
            - ./.env
        environment:
            - POSTGRES_HOST_AUTH_METHOD=trust
        volumes:
            - <
            - ./../../tmp/pgsql/certs:/var/lib/postgresql/certs:ro

    pgadmin:
        # http://localhost:5050/
        container_name: pgadmin
        image: dpage/pgadmin4
        restart: always
        env_file:
            - ./.env
        ports:
            - "5050:80"

