SAMPLES_DIR = ../../tmp/pytorch/cv1

download-samples: \
    echo $(SAMPLES_DIR) \
    mkdir -p $(SAMPLES_DR) \
    wget https://www.cis.upenn.edu/~jshi/ped_html/PennFudanPed.zip -P data \
    unzip PennFudanPed.zip -d $(SAMPLES_DIR)

