version: "3"

services:
    mssql:
        container_name: mssql
        hostname: mssql
        image: mcr.microsoft.com/mssql/server:2022-latest
        env_file:
            - ./.env
        ports:
            - "1433:1433"
        volumes:
            - ./../../tmp/mssql/data:/var/opt/mssql