version: '3'

services:
   teradata:
    image: tdqs
    container_name: teradata
    volumes:
      - ./../../tmp/teradata/:/etc/opt/teradata/rest/config
    ports:
      - "1080:1080"
      - "1443:1443"

volumes:
  tdqs-config:
